location = input("Give me a location")
famousperson = input("Give me a famous person")
adjective1 = input("Give me the first adjective")
sound1 = input("Give me a sound")
animal1 = input("Give me an animal")
animal2 = input("Give me another animal")
animal3 = input("Give me a third animal")
verb1 = input("Give me a verb")
typeofperson = input("Give me a type of person")
noun1 = input("Give me a noun")
verb2 = input("Give me another verb")
store = input("Give me a store")
people = input("Give me some people?")
alrightterrible = input("Is it alright or terrible?")
famouswoman = input("Name me a famous woman")
verb3 = input("Give me another verb")
group = input("Give me a group")
place = input("Give me a place")
game = input("Give me a game")
setting = input("Give me a setting")
edverb = input("Give me an -ed verb")
accomplishment = input("Give me an accomplishment")
pluralnoun = input("Give me a plural noun")
unsuccessfulathlete = input("Give me an unsuccessful athlete")
adjective2 = input("Give me one last adjective")

print("Just waking up in the" + location)
print("Gotta thank" + famousperson)
print("I don't know, but today seems kinda" + adjective1)
print("No" + sound1 + "from the" + animal1 + ", no smog")
print("and momma cooked a breakfast with no" + animal2)
print("I got my grub on, but I didnt" + animal3 + "out")
print("Finally got a call from a girl I want to" + verb1)
print("Hooked it up for later as I hit the door thinking, Will I live to see another" + typeofperson)
print("I gotta go cuz I got me a" + noun1)
print("and if I hit the switch I can make it" + verb2)
print("Had to stop at a" + store)
print("lookin in the mirror not a" + people + "in sight and everything is" + alrightterrible)
print("I got a beep from" + famouswoman + "and she can" + verb3 + "all night.")
print("Calling up the" + group + "and Im asking yall Which" + place + "are yall playin" + game)
print("Get me on the" + setting + "and Im in trouble")
print("Last week" + edverb + "around and got a" + accomplishment)
print("Freaking" + pluralnoun + "every way like" + unsuccessfulathlete)
print("I cant believe it was a" + adjective2 + "day")
